// fetch all universities list
export const LOADING_UNIVERSITIES = "LOADING_UNIVERSITIES";
export const SET_UNIVERISITIES = "SET_UNIVERISITIES";
// export const STACK_UNIVERSITIES = "STACK_UNIVERSITIES";
export const FAILED_UNIVERISITIES = "FAILED_UNIVERISITIES";
export const SEARCH_UNIVERSITIES = "SEARCH_UNIVERSITIES";


// fetch individual university
export const FETCH_UNIVERISITY_REQUEST = "FETCH_UNIVERISITY_REQUEST";
export const FETCH_UNIVERISITY_SUCCESS = "FETCH_UNIVERISITY_SUCCESS";
export const FETCH_UNIVERISITY_FAILED = "FETCH_UNIVERISITY_FAILED";

//log in, logout
export const authenticationTypes = {
    LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
    LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
    LOGIN_FAILURE: "USERS_LOGIN_FAILURE",
    LOGOUT: "USERS_LOGOUT"
};

// register
export const registerTypes = {
    REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
    REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
    REGISTER_FAILURE: "USERS_REGISTER_FAILURE"
};

//alerts
export const alertTypes = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR'
};

//universities
export const universityTypes = {
    UNIVERISITIES_REQUEST: "USERS_UNIVERISITIES_REQUEST",
    UNIVERISITIES_SUCCESS: "USERS_UNIVERISITIES_SUCCESS",
    UNIVERISITIES_FAILURE: "USERS_UNIVERISITIES_FAILURE"
};